name: curriculo_online
description: Um curriculo online para mostrar meu portfólio.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1
  go_router: ^5.2.0
  get_it: ^7.2.0
  responsive_framework: ^0.2.0
  google_fonts: ^4.0.1
  url_launcher: ^6.1.7
  flutter_html: ^2.2.1
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/foto.png
    - assets/images/projetos/cip/
    - assets/images/projetos/claro-lgpd/
    - assets/images/projetos/leagueOfLegends/
    - assets/images/projetos/mambo/
    - assets/images/projetos/meu-tecnico/
    - assets/images/projetos/mobileBus/
    - assets/images/projetos/proje-oi/
    - assets/images/projetos/tcc/
    - assets/images/projetos/fonteReiki/
    - assets/data/
